name: Checks

on: [push]

jobs:
  test-lint:
    name: Test and Lint
    runs-on: windows-latest
    steps:
      - name: Login to Docker
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Test
        shell: pwsh
        run: docker-compose run --rm app sh -c "python manage.py test"

      - name: Lint
        shell: pwsh
        run: docker-compose run --rm app sh -c "flake8"

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: path/to/test/results

      - name: Notify on Failure
        if: failure()
        uses: actions/github-script@v5
        with:
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '🚨 Workflow failed! Please check the logs.'
            })
