name: Checks

on: [push]

jobs:
  test-lint:
    name: Test and Lint
    runs-on: windows-latest
    steps:
      -  name: Login to Docker
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Test
        shell: pwsh
        run: docker-compose run --rm app sh -c "python manage.py test"

      - name: Lint
        shell: pwsh
        run: docker-compose run --rm app sh -c "flake
